ALTER TYPE "ActivityType" ADD VALUE 'MEMBER_ROLE_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'MEMBER_REMOVED';
ALTER TYPE "ActivityType" ADD VALUE 'INVITATION_REVOKED';
ALTER TYPE "ActivityType" ADD VALUE 'MEMBER_LEFT';
